# Generated by Django 4.2.3 on 2023-07-06 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id_medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField(null=True)),
                ('concentracion', models.CharField(max_length=50, null=True)),
                ('laboratorio', models.CharField(max_length=100, null=True)),
                ('proveedor', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id_medico', models.IntegerField(primary_key=True, serialize=False)),
                ('especialidad', models.CharField(max_length=100, null=True)),
                ('habilitado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.IntegerField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(max_length=20, null=True)),
                ('huella_dactilar', models.BinaryField(null=True)),
                ('habilitado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=100)),
                ('tipo_usuario', models.CharField(max_length=20)),
                ('habilitado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id_receta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(null=True)),
                ('habilitada', models.BooleanField(default=True)),
                ('medico_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.medico')),
                ('paciente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField(null=True)),
                ('genero', models.CharField(max_length=10, null=True)),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.roles')),
                ('id_usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='id_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.personas'),
        ),
        migrations.AddField(
            model_name='medico',
            name='id_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.personas'),
        ),
        migrations.CreateModel(
            name='Farmaceutico',
            fields=[
                ('id_farmaceutico', models.IntegerField(primary_key=True, serialize=False)),
                ('habilitado', models.BooleanField(default=True)),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.personas')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleReceta',
            fields=[
                ('id_detalle_receta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(null=True)),
                ('indicaciones', models.TextField(null=True)),
                ('medicamento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.medicamento')),
                ('receta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.receta')),
            ],
        ),
    ]
