# Generated by Django 4.2.3 on 2023-07-07 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallereceta',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='farmaceutico',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='medicamento',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='medico',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='personas',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='receta',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'managed': False},
        ),
    ]
