# Generated by Django 4.2.3 on 2023-07-07 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_detallereceta_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detallereceta',
            table='detallereceta',
        ),
        migrations.AlterModelTable(
            name='farmaceutico',
            table='farmaceutico',
        ),
        migrations.AlterModelTable(
            name='medicamento',
            table='medicamento',
        ),
        migrations.AlterModelTable(
            name='medico',
            table='medico',
        ),
        migrations.AlterModelTable(
            name='paciente',
            table='paciente',
        ),
        migrations.AlterModelTable(
            name='personas',
            table='personas',
        ),
        migrations.AlterModelTable(
            name='receta',
            table='receta',
        ),
        migrations.AlterModelTable(
            name='roles',
            table='roles',
        ),
        migrations.AlterModelTable(
            name='usuarios',
            table='usuarios',
        ),
    ]
